### ISSUE TITLE
为什么会出现这样的错误？我是初学者

### ISSUE THREAD

**Issue by reaCodes** [StephinChou/Pythonspider#2]
Traceback (most recent call last):
  File "C:\Users\reaCodes\Documents\Visual Studio 2015\Projects\Python\Python\taobaomm.py", line 3, in <module>
    from spider import SpiderHTML
  File "C:\Users\reaCodes\Documents\Visual Studio 2015\Projects\Python\Python\spider.py", line 5, in <module>
    from urllib import request
ImportError: cannot import name request

**Comment by StephinChou** [comment]
python版本一样的吗

**Comment by reaCodes** [comment]
@StephinChou 必须要3.4么，我用的是3.5版本

**Comment by StephinChou** [comment]
PYTHON兼容性很差，没琢磨过3.4和3.5的区别
